### ISSUE TITLE
Redshift connector step

### ISSUE THREAD

**Issue by JuhaKiili** [valohai/library-sandbox#1]
Reusable step for querying data from Redshift using SQL.

Parameters:
- SQL query
- Target datum alias

Output:
- CSV file

Relevant: https://help.valohai.com/hc/en-us/articles/4421460555409-Access-AWS-Redshift-from-an-execution

**Comment by JuhaKiili** [comment]
- [ ] Print output preview into logs
- [ ] Push valohai/redshift-connector docker image
- [ ] Make video

**Comment by JuhaKiili** [comment]
Results preview in logs

![Image](https://user-images.githubusercontent.com/1525350/220613212-4701b684-789e-4a76-8114-68ced025a4fe.png)

**Comment by akx** [comment]
Done via #4.
