### ISSUE TITLE
Handle falsy boolean environment variables better

### ISSUE THREAD

**Issue by tokkoro** [valohai/library-sandbox#22]
Now only empty value is seen as False and everything else is True like "0", "False".

Variables (in lower case) should be false for values: _empty_, n, no, f, false, off and 0

**Comment by DrazenDodik** [comment]
Can we unify this behavior with BigQuery
https://github.com/valohai/library-sandbox/blob/c58276aa260a2676d704ca27ab243e3b1bb4c4ae/connectors/steps/bigquery/query.py#L13
