### ISSUE TITLE
Keypair login for Snowflake connector

### ISSUE THREAD

**Issue by JuhaKiili** [valohai/library-sandbox#26]
@noora wrote

Snowflake allows setting up [keypair login](https://docs.snowflake.com/en/user-guide/key-pair-auth#step-4-assign-the-public-key-to-a-snowflake-user) instead of username/password. Some of our customers would like to have this possibility for the Snowflake connector. 

It would be great to have a similar option as what we now have for Redshift/BigQuery and using IAM for authentication that for example with a boolean the user could choose to use either password or keypair login. For this there should be a new environment variable field `SNOWSQL_PRIVATEKEY`. 

Snowflake docs for keypair authentication: https://docs.snowflake.com/en/developer-guide/python-connector/python-connector-example#using-key-pair-authentication-key-pair-rotation

**Comment by JuhaKiili** [comment]
Short description for implementation in case someone else takes this:

- [ ] Add dependency `cryptography` to `requirements.txt`
- [ ] Load the `SNOWSQL_PRIVATEKEY` and `SNOWSQL_PASSPHRASE` environment variables in `snowflake/query.py`
- [ ] Create `snowflake/connect.py` (look at `bigquery/connect.py` for inspiration)
- [ ] If there is private key, [load and transform](https://docs.snowflake.com/en/developer-guide/python-connector/python-connector-example#using-key-pair-authentication-key-pair-rotation) the key and call `snowflake.connector.connect()`
- [ ] If there is no private key, do what we currently do with login/password

**Comment by akx** [comment]
The cryptography stuff isn't strictly necessary though, there's no additional protection if the private key and the passphrase are submitted in the same request :)
